[package]
name = "uutils-args"
version = "0.1.0"
edition = "2021"
authors = ["Terts Diepraam"]
license = "MIT"

homepage = "https://github.com/tertsdiepraam/uutils-args"
repository = "https://github.com/tertsdiepraam/uutils-args"
readme = "README.md"

[lib]
proc-macro = true

[dependencies]
