[package]
name = "term_md"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nu-ansi-term = "0.46.0"
pulldown-cmark = "0.9.2"
unicode-width = "0.1.10"
